on:
  pull_request:
    branches:
      - main
      - DEV
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          changed-files: "true"
